# Generated by Django 6.0.4 on 2026-05-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-created'], 'verbose_name': 'تصویر', 'verbose_name_plural': 'تصویر ها'},
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['-created'], name='blog_image_created_a116df_idx'),
        ),
    ]
