# Generated by Django 6.0.4 on 2026-06-08 19:39

import django_jalali.db.models
import jdatetime
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_post_category_alter_image_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=django_jalali.db.models.jDateTimeField(default=jdatetime.datetime.now, verbose_name='تاریخ انتشار'),
        ),
    ]
